language: python
cache: pip
dist: xenial
matrix:
  fast_finish: true
  include:
    # TODO: uncomment when package will be compatible with python 3.4
    # - python: "3.4"
    #   env: DJANGO=1.11
    # - python: "3.4"
    #   env: DJANGO=2.0
    # - python: "3.4"

    - python: "3.5"
      env: DJANGO=1.11
    - python: "3.5"
      env: DJANGO=2.0
    - python: "3.5"
      env: DJANGO=2.1
    - python: "3.5"
      env: DJANGO=2.2

    - python: "3.6"
      env: DJANGO=1.11
    - python: "3.6"
      env: DJANGO=2.0
    - python: "3.6"
      env: DJANGO=2.1
    - python: "3.6"
      env: DJANGO=2.2
    - python: "3.6"
      env: DJANGO=master

    - python: "3.7"
      env: DJANGO=2.0
    - python: "3.7"
      env: DJANGO=2.1
    - python: "3.7"
      env: DJANGO=2.2
    - python: "3.7"
      env: DJANGO=master

  allow_failures:
    - env: DJANGO=master

install:
  - pip install tox tox-travis

script:
  - tox

notifications:
  email: false
