# Generated by Django 2.2 on 2019-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_hard',
            field=models.BooleanField(default=False),
        ),
    ]
