# Generated by Django 2.2 on 2019-07-14 11:39
from django.db import (
    migrations,
    models,
)


def censore_cheesy_words(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    Choice = apps.get_model('polls', 'Choice')
    _censore_all_cheesy_words(Question, 'question_text')
    _censore_all_cheesy_words(Choice, 'choice_text')


def _censore_all_cheesy_words(model_class, text_field):
    # imagine this replace names of all kind of cheeses with sequence of `*`
    (
        model_class.objects.select_for_update()
        .filter(**{f'{text_field}__icontains': 'cheese'})
        .update(**{
            text_field: models.functions.Replace(
                text_field,
                models.Value('cheese'),
                models.Value('******'),
            ),
        })
    )
    gjetost_related_texts = model_class.objects.filter(
            **{f'{text_field}__icontains': 'gjetost'},
    )
    if gjetost_related_texts.exists():
        raise ValueError(
            'Is `Gjetost` a real cheese? Review `Gjetost` related texts '
            'manually before running migration.'
        )


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0004_populate_question_difficulty_level_field'),
    ]
    operations = [
        migrations.RunPython(
            code=censore_cheesy_words,
            reverse_code=migrations.RunPython.noop,
        )
    ]
